version: 2
jobs:
  build:
    machine: true
    working_directory: /home/circleci/logspout
    environment:
      DEBUG: true
    steps:
      - checkout
      - run: |
          make circleci
      - run: |
          make lint-ci
      - run: |
          make build
      - run: |
          make build-custom
      - run: |
          make -e test-image-size
      - run: |
          make -e test
      - run: |
          make -e test-tls
      - run: |
          make -e test-healthcheck
      - run: |
          make -e test-custom
      - run: |
          make -e test-tls-custom
      - store_artifacts:
          path: build
          destination: build
      - deploy:
          name: release
          command: |
            if [ "${CIRCLE_BRANCH}" == "release" ]; then
              make release
            fi
  publish:
    machine:
      image: ubuntu-1604:202007-01
    working_directory: /home/circleci/logspout
    environment:
      DEBUG: true
    steps:
      - checkout
      - run: mkdir -vp ~/.docker/cli-plugins/
      - run: curl --silent -L --output ~/.docker/cli-plugins/docker-buildx https://github.com/docker/buildx/releases/download/v0.3.1/buildx-v0.3.1.linux-amd64
      - run: chmod a+x ~/.docker/cli-plugins/docker-buildx
      - run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      - run: docker run -it --rm --privileged tonistiigi/binfmt --install all
      - run: docker buildx create --use --name mybuilder
      - run: |
          docker buildx build --push --platform linux/arm64,linux/amd64 -t sakshi9715/logspout:${CIRCLE_BRANCH} -t sakshi9715/logspout:latest .
workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish
